// <auto-generated />
using System;
using Metrics.ADO.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metrics.ADO.Migrations
{
    [DbContext(typeof(ADOMetricsDbContext))]
    partial class ADOMetricsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Metrics.ADO.Models.WorkItemMetrics", b =>
                {
                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_item_id");

                    b.Property<int>("ChangesRequested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("changes_requested");

                    b.Property<DateTimeOffset>("ClosedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_date");

                    b.Property<int>("Commits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("commits");

                    b.Property<int>("Contributors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contributors");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<int>("LOC")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loc");

                    b.Property<float>("MaturityPercentage")
                        .HasColumnType("REAL")
                        .HasColumnName("maturity_percentage");

                    b.Property<TimeSpan>("PRCycleTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("pr_cycle_time");

                    b.Property<string>("ReleaseVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_version");

                    b.Property<int>("ReviewComments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_comments");

                    b.Property<string>("ShirtSize")
                        .HasColumnType("TEXT")
                        .HasColumnName("shirt_size");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT")
                        .HasColumnName("team");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TotalPrs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_prs");

                    b.HasKey("WorkItemId")
                        .HasName("pk_workitem_metrics");

                    b.HasIndex("Team")
                        .HasDatabaseName("ix_workitem_metrics_team");

                    b.HasIndex("Team", "CreatedDate", "ClosedDate")
                        .HasDatabaseName("ix_workitem_metrics_team_created_date_closed_date");

                    b.ToTable("workitem_metrics", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.ADO.Models.WorkItemSyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_sync_date");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("WorkItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_workitem_sync_status");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_workitem_sync_status_work_item_id");

                    b.ToTable("workitem_sync_status", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.DataMigrationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_on");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("migration_id");

                    b.Property<string>("MigrationType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("migration_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_datamigrationhistory_ado");

                    b.ToTable("datamigrationhistory_ado", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });
#pragma warning restore 612, 618
        }
    }
}
