// <auto-generated />
using System;
using Metrics.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Metrics.Migrations.DevExMetricPostgresDb
{
    [DbContext(typeof(DevExMetricDbContext))]
    [Migration("20260912160537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Metrics.Domain.CopilotReviewMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Comments")
                        .HasColumnType("integer")
                        .HasColumnName("comments");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("files_changed");

                    b.Property<int>("FilesReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("files_reviewed");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("integer")
                        .HasColumnName("pr_metric_id");

                    b.HasKey("Id")
                        .HasName("pk_copilotreviewmetrics");

                    b.HasIndex("PRMetricId")
                        .IsUnique()
                        .HasDatabaseName("ix_copilotreviewmetrics_pr_metric_id");

                    b.ToTable("copilotreviewmetrics", (string)null);
                });

            modelBuilder.Entity("Metrics.Domain.DataMigrationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("applied_on");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("migration_id");

                    b.Property<string>("MigrationType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("migration_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_datamigrationhistory");

                    b.HasIndex("TenantId", "MigrationId", "MigrationType")
                        .IsUnique()
                        .HasDatabaseName("ix_datamigrationhistory_tenant_id_migration_id_migration_type");

                    b.ToTable("datamigrationhistory", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.DevExMetricItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("ApproveTime")
                        .HasColumnType("interval")
                        .HasColumnName("approve_time");

                    b.Property<float?>("AvgReviewCommentsPerCommit")
                        .HasColumnType("real")
                        .HasColumnName("avg_review_comments_per_commit");

                    b.Property<int?>("CodeExcellenceRequestedChanges")
                        .HasColumnType("integer")
                        .HasColumnName("code_excellence_requested_changes");

                    b.Property<TimeSpan?>("CodingTime")
                        .HasColumnType("interval")
                        .HasColumnName("coding_time");

                    b.Property<TimeSpan?>("CycleTime")
                        .HasColumnType("interval")
                        .HasColumnName("cycle_time");

                    b.Property<int?>("InitialLinesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("initial_lines_changed");

                    b.Property<TimeSpan?>("LeadTime")
                        .HasColumnType("interval")
                        .HasColumnName("lead_time");

                    b.Property<float?>("MaturityPercentage")
                        .HasColumnType("real")
                        .HasColumnName("maturity_percentage");

                    b.Property<TimeSpan?>("MergeTime")
                        .HasColumnType("interval")
                        .HasColumnName("merge_time");

                    b.Property<int?>("OthersRequestedChanges")
                        .HasColumnType("integer")
                        .HasColumnName("others_requested_changes");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("integer")
                        .HasColumnName("pr_metric_id");

                    b.Property<string>("PRSize")
                        .HasColumnType("text")
                        .HasColumnName("pr_size");

                    b.Property<TimeSpan?>("PickupTime")
                        .HasColumnType("interval")
                        .HasColumnName("pickup_time");

                    b.Property<TimeSpan?>("ReviewTime")
                        .HasColumnType("interval")
                        .HasColumnName("review_time");

                    b.Property<int?>("SubsequentLinesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("subsequent_lines_changed");

                    b.Property<int?>("TeamRequestedChanges")
                        .HasColumnType("integer")
                        .HasColumnName("team_requested_changes");

                    b.Property<int?>("TotalLargeCommitComments")
                        .HasColumnType("integer")
                        .HasColumnName("total_large_commit_comments");

                    b.Property<int?>("TotalLargeCommits")
                        .HasColumnType("integer")
                        .HasColumnName("total_large_commits");

                    b.Property<int?>("TotalMediumCommitComments")
                        .HasColumnType("integer")
                        .HasColumnName("total_medium_commit_comments");

                    b.Property<int?>("TotalMediumCommits")
                        .HasColumnType("integer")
                        .HasColumnName("total_medium_commits");

                    b.Property<int?>("TotalReviewChangesRequested")
                        .HasColumnType("integer")
                        .HasColumnName("total_review_changes_requested");

                    b.Property<int?>("TotalReviewComments")
                        .HasColumnType("integer")
                        .HasColumnName("total_review_comments");

                    b.Property<int?>("TotalReviewCommentsAfterFinalApproval")
                        .HasColumnType("integer")
                        .HasColumnName("total_review_comments_after_final_approval");

                    b.Property<int?>("TotalSmallCommitComments")
                        .HasColumnType("integer")
                        .HasColumnName("total_small_commit_comments");

                    b.Property<int?>("TotalSmallCommits")
                        .HasColumnType("integer")
                        .HasColumnName("total_small_commits");

                    b.HasKey("Id")
                        .HasName("pk_devexmetricitem");

                    b.HasIndex("PRMetricId")
                        .IsUnique()
                        .HasDatabaseName("ix_devexmetricitem_pr_metric_id");

                    b.ToTable("devexmetricitem", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "DevExMetrics");
                });

            modelBuilder.Entity("Metrics.Domain.PRContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Commits")
                        .HasColumnType("integer")
                        .HasColumnName("commits");

                    b.Property<string>("Contributor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contributor");

                    b.Property<int>("LOC")
                        .HasColumnType("integer")
                        .HasColumnName("loc");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("integer")
                        .HasColumnName("pr_metric_id");

                    b.HasKey("Id")
                        .HasName("pk_contributor");

                    b.HasIndex("PRMetricId")
                        .HasDatabaseName("ix_contributor_pr_metric_id");

                    b.ToTable("contributor", (string)null);
                });

            modelBuilder.Entity("Metrics.Domain.PRMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("author");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("base_branch");

                    b.Property<int?>("ChangedFiles")
                        .HasColumnType("integer")
                        .HasColumnName("changed_files");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DraftTransitions")
                        .HasColumnType("integer")
                        .HasColumnName("draft_transitions");

                    b.Property<bool?>("IsFeature")
                        .HasColumnType("boolean")
                        .HasColumnName("is_feature");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("merged_at");

                    b.Property<string>("MergedBy")
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("merged_by");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pr_number");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext")
                        .HasColumnName("repository");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("citext")
                        .HasColumnName("state");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalComments")
                        .HasColumnType("integer")
                        .HasColumnName("total_comments");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("integer")
                        .HasColumnName("total_commits");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer")
                        .HasColumnName("total_lines");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkItemId")
                        .HasMaxLength(20)
                        .HasColumnType("citext")
                        .HasColumnName("work_item_id");

                    b.Property<string>("WorkItemId2")
                        .HasMaxLength(20)
                        .HasColumnType("citext")
                        .HasColumnName("work_item_id2");

                    b.HasKey("Id")
                        .HasName("pk_metrics");

                    b.HasIndex("Author")
                        .HasDatabaseName("ix_metrics_author");

                    b.HasIndex("PrNumber")
                        .HasDatabaseName("ix_metrics_pr_number");

                    b.HasIndex("Repository")
                        .HasDatabaseName("ix_metrics_repository");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_metrics_state");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_metrics_team_id");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_metrics_work_item_id");

                    b.HasIndex("WorkItemId2")
                        .HasDatabaseName("ix_metrics_work_item_id2");

                    b.HasIndex("CreatedAt", "Author")
                        .HasDatabaseName("ix_metrics_created_at_author");

                    b.HasIndex("CreatedAt", "TeamId")
                        .HasDatabaseName("ix_metrics_created_at_team_id");

                    b.ToTable("metrics", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.PRReviewerMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Approved")
                        .HasColumnType("integer")
                        .HasColumnName("approved");

                    b.Property<float?>("AverageResponseTimeHours")
                        .HasColumnType("real")
                        .HasColumnName("average_response_time_hours");

                    b.Property<int?>("ChangesRequested")
                        .HasColumnType("integer")
                        .HasColumnName("changes_requested");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("integer")
                        .HasColumnName("pr_metric_id");

                    b.Property<int?>("ReviewComments")
                        .HasColumnType("integer")
                        .HasColumnName("review_comments");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewer");

                    b.Property<int?>("ReviewsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_requested");

                    b.Property<int?>("ReviewsSubmitted")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_submitted");

                    b.HasKey("Id")
                        .HasName("pk_pr_reviewer_metrics");

                    b.HasIndex("PRMetricId", "Reviewer")
                        .IsUnique()
                        .HasDatabaseName("ix_pr_reviewer_metrics_pr_metric_id_reviewer");

                    b.ToTable("pr_reviewer_metrics", (string)null);
                });

            modelBuilder.Entity("Metrics.Domain.ReviewerDailyMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Approved")
                        .HasColumnType("integer")
                        .HasColumnName("approved");

                    b.Property<float?>("AverageResponseTimeHours")
                        .HasColumnType("real")
                        .HasColumnName("average_response_time_hours");

                    b.Property<int?>("ChangesRequested")
                        .HasColumnType("integer")
                        .HasColumnName("changes_requested");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("integer")
                        .HasColumnName("pr_metric_id");

                    b.Property<int?>("ReviewComments")
                        .HasColumnType("integer")
                        .HasColumnName("review_comments");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewer");

                    b.Property<int?>("ReviewsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_requested");

                    b.Property<int?>("ReviewsSubmitted")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_submitted");

                    b.HasKey("Id")
                        .HasName("pk_reviewer_daily_metrics");

                    b.HasIndex("PRMetricId", "Reviewer", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewer_daily_metrics_pr_metric_id_reviewer_date");

                    b.ToTable("reviewer_daily_metrics", (string)null);
                });

            modelBuilder.Entity("Metrics.Domain.ReviewerMonthlyMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRatePercentage")
                        .HasColumnType("integer")
                        .HasColumnName("approval_rate_percentage");

                    b.Property<int?>("Approved")
                        .HasColumnType("integer")
                        .HasColumnName("approved");

                    b.Property<float>("AverageCommentCount")
                        .HasColumnType("real")
                        .HasColumnName("average_comment_count");

                    b.Property<float?>("AverageResponseTimeHours")
                        .HasColumnType("real")
                        .HasColumnName("average_response_time_hours");

                    b.Property<int?>("ChangesRequested")
                        .HasColumnType("integer")
                        .HasColumnName("changes_requested");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<int>("CommentCountWhenReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count_when_reviewed");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("PrsCommented")
                        .HasColumnType("integer")
                        .HasColumnName("prs_commented");

                    b.Property<int>("PrsForApprovalRate")
                        .HasColumnType("integer")
                        .HasColumnName("prs_for_approval_rate");

                    b.Property<int>("PrsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("prs_requested");

                    b.Property<int>("PrsReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("prs_reviewed");

                    b.Property<int>("PrsReviewedWithComments")
                        .HasColumnType("integer")
                        .HasColumnName("prs_reviewed_with_comments");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("repository");

                    b.Property<int?>("ReviewComments")
                        .HasColumnType("integer")
                        .HasColumnName("review_comments");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewer");

                    b.Property<int?>("ReviewsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_requested");

                    b.Property<int?>("ReviewsSubmitted")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_submitted");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalReviewDays")
                        .HasColumnType("integer")
                        .HasColumnName("total_review_days");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_reviewer_monthly_metrics");

                    b.HasIndex("Reviewer", "Repository", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewer_monthly_metrics_reviewer_repository_month_year");

                    b.ToTable("reviewer_monthly_metrics", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.ReviewerSprintMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRatePercentage")
                        .HasColumnType("integer")
                        .HasColumnName("approval_rate_percentage");

                    b.Property<int?>("Approved")
                        .HasColumnType("integer")
                        .HasColumnName("approved");

                    b.Property<float>("AverageCommentCount")
                        .HasColumnType("real")
                        .HasColumnName("average_comment_count");

                    b.Property<float?>("AverageResponseTimeHours")
                        .HasColumnType("real")
                        .HasColumnName("average_response_time_hours");

                    b.Property<int?>("ChangesRequested")
                        .HasColumnType("integer")
                        .HasColumnName("changes_requested");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<int>("CommentCountWhenReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count_when_reviewed");

                    b.Property<int>("PrsCommented")
                        .HasColumnType("integer")
                        .HasColumnName("prs_commented");

                    b.Property<int>("PrsForApprovalRate")
                        .HasColumnType("integer")
                        .HasColumnName("prs_for_approval_rate");

                    b.Property<int>("PrsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("prs_requested");

                    b.Property<int>("PrsReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("prs_reviewed");

                    b.Property<int>("PrsReviewedWithComments")
                        .HasColumnType("integer")
                        .HasColumnName("prs_reviewed_with_comments");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("repository");

                    b.Property<int?>("ReviewComments")
                        .HasColumnType("integer")
                        .HasColumnName("review_comments");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewer");

                    b.Property<int?>("ReviewsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_requested");

                    b.Property<int?>("ReviewsSubmitted")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_submitted");

                    b.Property<int>("SprintNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sprint_number");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalReviewDays")
                        .HasColumnType("integer")
                        .HasColumnName("total_review_days");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_reviewer_sprint_metrics");

                    b.HasIndex("Reviewer", "Repository", "SprintNumber", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewer_sprint_metrics_reviewer_repository_sprint_number_y");

                    b.ToTable("reviewer_sprint_metrics", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.RunStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int?>("PRNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pr_number");

                    b.Property<string>("Repository")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("repository");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_runstatus");

                    b.HasIndex("Repository", "PRNumber")
                        .HasDatabaseName("ix_runstatus_repository_pr_number");

                    b.ToTable("runstatus", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("region");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ValueStream")
                        .HasMaxLength(50)
                        .HasColumnType("citext")
                        .HasColumnName("value_stream");

                    b.HasKey("Id")
                        .HasName("pk_team");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_team_name");

                    b.HasIndex("Name", "ValueStream", "Region")
                        .IsUnique()
                        .HasDatabaseName("ix_team_name_value_stream_region");

                    b.ToTable("team", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("Metrics.Domain.CopilotReviewMetrics", b =>
                {
                    b.HasOne("Metrics.Domain.PRMetrics", "PRMetric")
                        .WithOne("CopilotReviewMetrics")
                        .HasForeignKey("Metrics.Domain.CopilotReviewMetrics", "PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_copilotreviewmetrics_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.Domain.DevExMetricItem", b =>
                {
                    b.HasOne("Metrics.Domain.PRMetrics", "PRMetric")
                        .WithOne("DevExMetricItem")
                        .HasForeignKey("Metrics.Domain.DevExMetricItem", "PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devexmetricitem_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.Domain.PRContributor", b =>
                {
                    b.HasOne("Metrics.Domain.PRMetrics", "PRMetric")
                        .WithMany("Contributors")
                        .HasForeignKey("PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contributor_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.Domain.PRMetrics", b =>
                {
                    b.HasOne("Metrics.Domain.Team", "Team")
                        .WithMany("Metrics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_metrics_team_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Metrics.Domain.PRReviewerMetrics", b =>
                {
                    b.HasOne("Metrics.Domain.PRMetrics", "PRMetric")
                        .WithMany("ReviewerMetrics")
                        .HasForeignKey("PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pr_reviewer_metrics_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.Domain.ReviewerDailyMetrics", b =>
                {
                    b.HasOne("Metrics.Domain.PRMetrics", "PRMetric")
                        .WithMany("ReviewerDailyMetrics")
                        .HasForeignKey("PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewer_daily_metrics_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.Domain.PRMetrics", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("CopilotReviewMetrics")
                        .IsRequired();

                    b.Navigation("DevExMetricItem")
                        .IsRequired();

                    b.Navigation("ReviewerDailyMetrics");

                    b.Navigation("ReviewerMetrics");
                });

            modelBuilder.Entity("Metrics.Domain.Team", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
