// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metrics.Migrations
{
    [DbContext(typeof(DevExMetricDbContext))]
    [Migration("20250815043525_AddCompositeIndex")]
    partial class AddCompositeIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Metrics.CopilotReviewMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comments");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("files_changed");

                    b.Property<int>("FilesReviewed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("files_reviewed");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_metric_id");

                    b.HasKey("Id")
                        .HasName("pk_copilotreviewmetrics");

                    b.HasIndex("PRMetricId")
                        .IsUnique()
                        .HasDatabaseName("ix_copilotreviewmetrics_pr_metric_id");

                    b.ToTable("copilotreviewmetrics", (string)null);
                });

            modelBuilder.Entity("Metrics.DevExMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_metric_id");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_metricitem");

                    b.HasIndex("PRMetricId")
                        .HasDatabaseName("ix_metricitem_pr_metric_id");

                    b.ToTable("metricitem", (string)null);
                });

            modelBuilder.Entity("Metrics.PRContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Commits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("commits");

                    b.Property<string>("Contributor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("contributor");

                    b.Property<int>("LOC")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loc");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_metric_id");

                    b.HasKey("Id")
                        .HasName("pk_contributor");

                    b.HasIndex("PRMetricId")
                        .HasDatabaseName("ix_contributor_pr_metric_id");

                    b.ToTable("contributor", (string)null);
                });

            modelBuilder.Entity("Metrics.PRMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("author")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("base_branch")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DraftTransitions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("draft_transitions");

                    b.Property<bool?>("IsFeature")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_feature");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("merged_at");

                    b.Property<string>("MergedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("merged_by")
                        .UseCollation("NOCASE");

                    b.Property<int>("PrNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_number");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("repository")
                        .UseCollation("NOCASE");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("state")
                        .UseCollation("NOCASE");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("team_id");

                    b.Property<int>("TotalComments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_comments");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_commits");

                    b.Property<int>("TotalLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_lines");

                    b.HasKey("Id")
                        .HasName("pk_metrics");

                    b.HasIndex("Author")
                        .HasDatabaseName("ix_metrics_author");

                    b.HasIndex("PrNumber")
                        .HasDatabaseName("ix_metrics_pr_number");

                    b.HasIndex("Repository")
                        .HasDatabaseName("ix_metrics_repository");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_metrics_state");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_metrics_team_id");

                    b.HasIndex("CreatedAt", "Author")
                        .HasDatabaseName("ix_metrics_created_at_author");

                    b.HasIndex("CreatedAt", "TeamId")
                        .HasDatabaseName("ix_metrics_created_at_team_id");

                    b.ToTable("metrics", (string)null);
                });

            modelBuilder.Entity("Metrics.PRReviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("login")
                        .UseCollation("NOCASE");

                    b.HasKey("Id")
                        .HasName("pk_reviewer");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewer_login");

                    b.ToTable("reviewer", (string)null);
                });

            modelBuilder.Entity("Metrics.PRReviewerMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Approved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved");

                    b.Property<int>("ChangesRequested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("changes_requested");

                    b.Property<int>("PRMetricId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_metric_id");

                    b.Property<int>("PRReviewerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_reviewer_id");

                    b.Property<int>("ReviewComments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("review_comments");

                    b.Property<int>("Reviews")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reviews");

                    b.HasKey("Id")
                        .HasName("pk_reviewermetrics");

                    b.HasIndex("PRMetricId")
                        .HasDatabaseName("ix_reviewermetrics_pr_metric_id");

                    b.HasIndex("PRReviewerId")
                        .HasDatabaseName("ix_reviewermetrics_pr_reviewer_id");

                    b.ToTable("reviewermetrics", (string)null);
                });

            modelBuilder.Entity("Metrics.RunStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at");

                    b.HasKey("Id")
                        .HasName("pk_runstatus");

                    b.ToTable("runstatus", (string)null);
                });

            modelBuilder.Entity("Metrics.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("region")
                        .UseCollation("NOCASE");

                    b.Property<string>("ValueStream")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("value_stream")
                        .UseCollation("NOCASE");

                    b.HasKey("Id")
                        .HasName("pk_team");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_team_name");

                    b.HasIndex("Name", "ValueStream", "Region")
                        .IsUnique()
                        .HasDatabaseName("ix_team_name_value_stream_region");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("Metrics.CopilotReviewMetrics", b =>
                {
                    b.HasOne("Metrics.PRMetrics", "PRMetric")
                        .WithOne("CopilotReviewMetrics")
                        .HasForeignKey("Metrics.CopilotReviewMetrics", "PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_copilotreviewmetrics_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.DevExMetric", b =>
                {
                    b.HasOne("Metrics.PRMetrics", "PRMetric")
                        .WithMany("DevExMetrics")
                        .HasForeignKey("PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metricitem_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.PRContributor", b =>
                {
                    b.HasOne("Metrics.PRMetrics", "PRMetric")
                        .WithMany("Contributors")
                        .HasForeignKey("PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contributor_metrics_pr_metric_id");

                    b.Navigation("PRMetric");
                });

            modelBuilder.Entity("Metrics.PRMetrics", b =>
                {
                    b.HasOne("Metrics.Team", "Team")
                        .WithMany("Metrics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_metrics_team_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Metrics.PRReviewerMetrics", b =>
                {
                    b.HasOne("Metrics.PRMetrics", "PRMetric")
                        .WithMany("ReviewerMetrics")
                        .HasForeignKey("PRMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewermetrics_metrics_pr_metric_id");

                    b.HasOne("Metrics.PRReviewer", "PRReviewer")
                        .WithMany("ReviewerMetrics")
                        .HasForeignKey("PRReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reviewermetrics_reviewer_pr_reviewer_id");

                    b.Navigation("PRMetric");

                    b.Navigation("PRReviewer");
                });

            modelBuilder.Entity("Metrics.PRMetrics", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("CopilotReviewMetrics")
                        .IsRequired();

                    b.Navigation("DevExMetrics");

                    b.Navigation("ReviewerMetrics");
                });

            modelBuilder.Entity("Metrics.PRReviewer", b =>
                {
                    b.Navigation("ReviewerMetrics");
                });

            modelBuilder.Entity("Metrics.Team", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
